name = "HierarchicalSchrodinger"
uuid = "45e3ba60-8094-4aa0-8e69-e67dfb156f33"
authors = ["john.papad "]
version = "0.0.1"

[deps]
ClassicalOrthogonalPolynomials = "b30e2e7b-c4ee-47da-9d5f-2c5c27239acd"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MatrixFactorizations = "a3b82374-2e81-5b9e-98ce-41277c0e4c87"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
RadialPiecewisePolynomials = "7dab568b-3cf7-4f91-a977-b4631dfca174"

[compat]
ClassicalOrthogonalPolynomials = "0.13"
DelimitedFiles = "1"
LaTeXStrings = "1"
MatrixFactorizations = "3.0.0"
Plots = "1"
PyPlot = "2"
RadialPiecewisePolynomials = "0.1.3"
julia = "1.10"